-- phpMyAdmin SQL Dump
-- version 3.3.7deb5
-- http://www.phpmyadmin.net
--
-- Anamakine: localhost
-- Üretim Zamanı: 06 Ekim 2011 saat 01:03:23
-- Sunucu sürümü: 5.1.49
-- PHP Sürümü: 5.3.3-7+squeeze1

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Veritabanı: `sim`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `node`
--

CREATE TABLE IF NOT EXISTS `node` (
  `nid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id` int(10) unsigned NOT NULL,
  `title` varchar(250) COLLATE utf8_turkish_ci DEFAULT NULL,
  `media` varchar(100) COLLATE utf8_turkish_ci DEFAULT NULL,
  `content` varchar(10000) COLLATE utf8_turkish_ci DEFAULT NULL,
  `question` varchar(250) COLLATE utf8_turkish_ci DEFAULT NULL,
  `options` varchar(10000) COLLATE utf8_turkish_ci DEFAULT NULL,
  `ntype` varchar(5) COLLATE utf8_turkish_ci DEFAULT NULL,
  `parent` int(10) unsigned DEFAULT NULL,
  `isOnset` tinyint(1) DEFAULT NULL,
  `isWrong` tinyint(1) DEFAULT NULL,
  `cid` int(11) NOT NULL,
  PRIMARY KEY (`nid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_turkish_ci AUTO_INCREMENT=37 ;

--
-- Tablo döküm verisi `node`
--

INSERT INTO `node` (`nid`, `id`, `title`, `media`, `content`, `question`, `options`, `ntype`, `parent`, `isOnset`, `isWrong`, `cid`) VALUES
(10, 4, 'Hata: olay yerine gitmek', NULL, '', 'Olay yerine gidilmeyerek hekimin hangi yasal sorumluluğu yerine getirilmemiş oldu?', 'a:1:{i:0;a:7:{s:9:"link_text";s:73:"Aşağıdaki boşluğa yanıtınız yazıp gönder tuşuna tıklayınız.";s:9:"node_link";s:1:"5";s:8:"response";s:187:"Hekimin yasal sorumluluklarından en önemli bir tanesi acil hastaya müdahele zorunluluğudur. Bu nedenle hastanın acil tşhis ve tedavisine yönelik işlemin yapılması gerekmektedir.";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(9, 3, 'Doğru: devam', NULL, '', 'Olay yerine gitmeniz, hekimin yasal sorumluluklarından hangisi içine girer?', 'a:1:{i:0;a:7:{s:9:"link_text";s:71:"Yanıtınızı aşağıdaki alana yazıp gönder tuşuna tıklayınız.";s:9:"node_link";s:1:"5";s:8:"response";s:187:"Hekimin yasal sorumluluklarından en önemli bir tanesi acil hastaya müdahele zorunluluğudur. Bu nedenle hastanın acil tşhis ve tedavisine yönelik işlemin yapılması gerekmektedir.";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(7, 1, 'Giriş', '_n00007.jpg', '33 yaşındaki Hamdi Mersin, çiçek serasında ilaçlama yaptıktan sonra, çiçek serasının tavanındaki bir hasarı gidermek için merdivene çıkarken, kendini kötü hissetmiş, bulantısı olmuş, kısa süreli bir baygınlık geçirmiş, gözleri kararmış ve  5 basamak yukarıdan yere düşmüştür. Düşme sırasında boyun ve bel bölgesini zemindeki beton çıkıntıya çarpmıştır. Kafasına ise bir darbe almadığını belirtmiştir. Doktor olarak görev yaptığınız, çiçek serasının 50 metre uzağında bulunan  aile hekimliği merkezinden, hastaya müdahale etmeniz için çağrıldınız.::', 'Bundan sonraki yaklaşımınız ne olur?', 'a:3:{i:0;a:7:{s:9:"link_text";s:238:"Hastalara ilk acil müdahalenin, 112 acil ambulans merkezi tarafından yapılmasının gerektiğini, bu nedenle aile hekimliği kliniğini terk edemeyeceğimi belirtirim. Bu belirtilen hususu ilgili klinik muayene defterine kayıt ederim.";s:9:"node_link";s:1:"2";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:1:"5";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:201:"Hastanın durumunu görmek ve gerekirse tıbbi müdahale etmek için, varsa yardımcı sağlık personeli eşliğinde, yoksa bizzat kendim acil hastaya müdahale etmek için çiçek serasına giderim. ";s:9:"node_link";s:1:"3";s:8:"response";s:0:"";s:4:"odul";s:1:"6";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:2;a:7:{s:9:"link_text";s:105:"Aile hekimliği merkezi sorumlusunun resmi iznini beklerim. Gerekli izin alınınca olay yerine giderim. ";s:9:"node_link";s:1:"4";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:1:"5";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 1, 1, 0, 1),
(8, 2, 'Hata: acil mudahele', NULL, '', 'Olay yerine gidilmeyerek hekimin hangi yasal sorumluluğu yerine getirmemiş oldunuz?', 'a:1:{i:0;a:7:{s:9:"link_text";s:71:"Yanıtınızı aşağıdaki boşluğu basıp gönder tuşuna basınız.";s:9:"node_link";s:1:"5";s:8:"response";s:187:"Hekimin yasal sorumluluklarından en önemli bir tanesi acil hastaya müdahele zorunluluğudur. Bu nedenle hastanın acil tşhis ve tedavisine yönelik işlemin yapılması gerekmektedir.";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(11, 5, 'Acil hastaya müdahele prensipleri', '_n00011.jpg', '5 dakika içinde gerekli tıbbi aletleriniz ile olay yerine ulaştınız. 112 Ambulans merkezine haber verilmesini sağladınız. Sonrasında bir paramedik sağlık memuru da, size yardımcı olabileceğini belirterek sizinle beraber hasta başına geldi. Hasta seranın içinde, açık kapının yanındaki kanepede uzanmaktadır. Halen bulantısı olduğunu belirten hasta, doktor bey bana yardımcı olur musunuz, kendimi iyi hissetmiyorum  demektedir ? Kanepenin yanında, ağzı açık metal kutular bulunmaktadır. Hasta karın ağrısı şikayetininde olduğunu belirtmekte ve yardım istemektedir. <br>\r\nBundan sonraki aşamada ne yaparsınız?::,,\r\n\r\n1- Olay yeri ve çevresini hızlıca incelerim. Aynı anda havayolu, solunum dolaşım kontrolü için hastayı değerlendiririm. Kanepe yanındaki teneke kutuların ne için kullanıldığını sorarım.::\r\n\r\n2- Cevap: Doktor bey bunlar senelerdir çiçek serasında kullandığımız tarım ilaçlarının kutuları. Çiçeklerin üzerinde yerleşen böceklerin öldürülmesi için kullanıyoruz. Ancak bugün ilaçlamada kullanılan k,,', 'Bundan sonraki yaklaşımınız ne olur?', 'a:2:{i:0;a:7:{s:9:"link_text";s:237:"Hastanın zehirlenmiş olabileceğini de düşünüp, yeni kullanıldığı belirtilen tarım ilacı kutusunu da getirmelerini isterim ve sera içinde kanepede yatan hastanın öyküsünü öyküsünü alıp, fizik muayenesine geçerim. ";s:9:"node_link";s:1:"6";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:1:"3";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:62:"Hastanın öyküsünü alıp, muayenesini yapmadan önce:.....";s:9:"node_link";s:1:"7";s:8:"response";s:13:"doğru yanıt";s:4:"odul";s:1:"3";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(12, 6, 'Hata: transport gerekirdi', NULL, 'Doktor bey öncelikle hastanın ve sağlık çalışanlarının güvenliği için hastanın seradan uzak havadar bir yere transportunu öneriyorum.', '', 'a:1:{i:0;a:7:{s:9:"link_text";s:20:"Transport gerekirdi.";s:9:"node_link";s:1:"8";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(13, 7, 'Acil hastaya yaklaşımda çevre güvenliği', NULL, 'Hastanın ve sağlık çalışanlarının güveliği için öncelikle hastanın sera içinde yattığı yerden, havadar ve açık bir alana nakli gerekmektedir. ', '', 'a:1:{i:0;a:7:{s:9:"link_text";s:12:"Transport et";s:9:"node_link";s:1:"8";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(14, 8, 'Hastanın taşınması', '_n00014.jpg', 'Hasta taşınmasında yakınları, hastayı battaniye üzerine taşımak istemektedir.', 'Hastanın transportu sırasında nelere dikkat edersiniz?', 'a:2:{i:0;a:7:{s:9:"link_text";s:142:"Hastanın, hasta yakınlarının da yardımı ile bir battaniye üzerine alınarak, yukarıda gösterilen şekilde taşınmasını sağlarım.";s:9:"node_link";s:1:"9";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:1:"2";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:39:"Hastanın transportu sırasında önce,";s:9:"node_link";s:2:"10";s:8:"response";s:13:"doğru yanıt";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(15, 9, 'Hata: boyunluk', '_n00015.jpg', 'Doktor bey öncelikle hastanın boynuna boyunluk takılması ve sert taşıma tahtası üzerinde olası boyun ve bel zedelenmesine yönelik olarak dikkatlice taşınmasını öneriyorum.', '', 'a:1:{i:0;a:7:{s:9:"link_text";s:32:"Devam etmek için tıklayınız.";s:9:"node_link";s:2:"10";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(16, 10, 'Öykü', '_n00016.jpg', 'Öncelikle hastanın boynuna boyunluk takılması ve sert taşıma tahtası üzerinde olası boyun ve bel zedelenmesine yönelik olarak dikkatlice taşınması gerekmektedir.Bu işlem acil müdahale edilen hastanın taşınmasında dikkat edilmesi gereken temel ilkelerdir. \r\n\r\nHastanın uygun şartlarda transportu acil olarak sağlandı. Sonrasında havayolu, solunum ve dolaşım değerlendirldi. Olayın öyküsü soruldu.<br>\r\n\r\nResimde görüldüğü şekilde sera içinde ilaçlama yaptığını, sonrasında bulantı hissinin olduğunu, ancak işlerini bugün tamamlaması gerektiğini bu nedenle seranın içinde tamirat işi için çıktığı merdiven üzerinde iken fenalaşıp 5 basamaklı merdivenden düştüğünü, seranın zemininde bulunan beton çıktıya çarptığını, boynunu ve belini incittiğini, halen bulantısı ve terlemeleri olduğunu belirtti. ', 'Sera çalışanının mevcut resim ve öykü kayıtları doğrultusunda şikayetlerine neden olabilecek nedenler nelerdir?', 'a:1:{i:0;a:7:{s:9:"link_text";s:70:"Yanıtınızı aşağıdaki alana girip gönder tuşuna tıklayınız.";s:9:"node_link";s:2:"11";s:8:"response";s:13:"doğru yanıt";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(17, 11, 'Öntanı', NULL, 'Halen açık alanda bir sert bir zemin üzerinde yatan hastanın gömleğinin yaka bölgesinde boyun bölgesindeki  künt travmatik yaralanma sonucu meydana gelen deri abrazyonundan kaynaklanan kan bulaşı görülmekte, ancak aktif kanama izlenmemektedir.', ' Düşündüğünüz ön tanılar doğrultusunda, hastanın tedavisinde acilen yapılması gereken hangi işlem hastanın yaşamının kurtulması açısından önemlidir ?', 'a:2:{i:0;a:7:{s:9:"link_text";s:292:"Hastanın gömleğinin düğmelerini açmasını söyler, pantolonunu çıkartmasını söyleyip,  tüm vücudu hızlıca inceler, fizik muayenesini dikkatlice yaparak,  patolojik lezyonları not ederim. Hastanın,elbiselerini tekrar giymesi için yakınlarının yardım etmesini sağlarım.";s:9:"node_link";s:2:"12";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:1:"2";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:11:"Öncelikle,";s:9:"node_link";s:2:"13";s:8:"response";s:13:"doğru yanıt";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(18, 12, 'Hata: elbiseler', NULL, 'Elbiselerini çıkartmak çok önemlidir.', '', 'a:1:{i:0;a:7:{s:9:"link_text";s:32:"Devam etmek için tıklayınız.";s:9:"node_link";s:2:"13";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(19, 13, 'Tetkik', NULL, 'Hastanın gelen ambulans ile tam teşekkülü devlet hastanesi acil servisine sevki gerçekleşmiştir.  Ambulans gelene kadar bol ılık su ile vücudu yıkanmış ve üzerine temiz bir çarşaf örtülmüştür. Tarım ilacı ile kontaminasyon şüphesi olan elbiseleri imha/analiz edilmek üzere tehlikeli tıbbi atık çöpüne atılmıştır.', 'Acil serviste bu hastaya yönelik olarak hangi tetkikleri istersiniz?', 'a:4:{i:0;a:7:{s:9:"link_text";s:15:"Rutin biyokimya";s:9:"node_link";s:2:"14";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:24:"Kan kolinesteraz düzeyi";s:9:"node_link";s:2:"15";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:2;a:7:{s:9:"link_text";s:25:"Direkt Radyografi Tetkiki";s:9:"node_link";s:2:"16";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:3;a:7:{s:9:"link_text";s:36:"Tedavi önerisi için tıklayınız.";s:9:"node_link";s:2:"17";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(20, 14, 'Rutin biyokimya', NULL, 'Sonuçlar: ...', '', 'a:2:{i:0;a:7:{s:9:"link_text";s:30:"Başka tetkik yaptırmak için";s:9:"node_link";s:2:"13";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:21:"Tedavi önerisi için";s:9:"node_link";s:2:"17";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(21, 15, 'Kan kolinesteraz düzeyi', NULL, 'Sonuçlar: ...', '', 'a:2:{i:0;a:7:{s:9:"link_text";s:30:"Başka tetkik yaptırmak için";s:9:"node_link";s:2:"13";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:21:"Tedavi önerisi için";s:9:"node_link";s:2:"17";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(22, 16, 'Direkt Grafiği', NULL, 'Direkt Grafi Sonucunu <a href=/public/pdf/direkt-grafi.pdf>tıklayınız</a>.', '', 'a:2:{i:0;a:7:{s:9:"link_text";s:30:"Başka tetkik yaptırmak için";s:9:"node_link";s:2:"13";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:21:"Tedavi önerisi için";s:9:"node_link";s:2:"17";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(23, 17, 'drug', NULL, 'Tarım ilacı zehirlenmesine yönelik tedavi yaklaşımınızı (Basamaklar halinde belirtin) belirtiniz. Hangi ilacı hangi dozda hangi yolla verilmesini önerirsiniz.', 'Hangi ilaçları önerirsiniz?', 'a:1:{i:0;a:5:{s:9:"link_text";s:34:"aşağıda ki kutuda seçim yapın";s:9:"node_link";s:2:"26";s:8:"response";a:2:{i:0;s:3:"117";i:1;s:4:"2248";}s:4:"odul";s:1:"5";s:4:"ceza";s:1:"1";}}', 'drug', 0, 0, 0, 1),
(24, 18, 'Tramva', NULL, '::', 'Travmaya yönelik hangi incelemeleri yaparsınız?', 'a:1:{i:0;a:7:{s:9:"link_text";s:70:"Yanıtınızı aşağıdaki alana girip gönder tuşuna tıklayınız.";s:9:"node_link";s:2:"19";s:8:"response";s:13:"doğru yanıt";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(25, 19, 'Görsel Tetkik', NULL, 'İstenen tetkik sonuçlarını değerlendirin? ', '', 'a:4:{i:0;a:7:{s:9:"link_text";s:17:"Radyoloji tetkiki";s:9:"node_link";s:2:"20";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:16:"Boyun omur filmi";s:9:"node_link";s:2:"21";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:2;a:7:{s:9:"link_text";s:11:"XYZ tetkiki";s:9:"node_link";s:2:"24";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:3;a:7:{s:9:"link_text";s:71:"Başka tetkik istemiyorsanız. Yorumlamaya geçmek için tıklayınız.";s:9:"node_link";s:2:"25";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(26, 20, 'Radyoloji Tetkik Sonuçları', '_n00026.jpg', 'Sonuçlar: <br>\r\n\r\nbel ve göğüs omur filmi: normal <br>\r\nKafa grafisi: Kırık Yok. \r\n', '', 'a:2:{i:0;a:7:{s:9:"link_text";s:34:"Başka tetkik için tıklayınız.";s:9:"node_link";s:2:"19";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:71:"Başka tetkik istemiyorsanız. Yorumlamaya geçmek için tıklayınız.";s:9:"node_link";s:2:"25";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(27, 21, 'Boyun Omur Filmi ', '_n00027.jpg', 'Resim üzerinde işaretleyiniz.', '', 'a:1:{i:0;a:7:{s:9:"link_text";s:12:"Değerlendir";s:9:"node_link";s:2:"23";s:8:"response";s:6:"sdada ";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(28, 22, 'Raporlama', NULL, 'Burada RAPOR sunulacak.', '', 'a:1:{i:0;a:5:{s:9:"link_text";s:34:"Başa dönmek için tıklayınız.";s:9:"node_link";s:1:"1";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";}}', 'end', 0, 0, 0, 1),
(29, 23, 'Boyun Omur Filmi Değerlendirme', '_n00029.jpg', 'xxx i işaretlemeniz beklenirdi.', '', 'a:2:{i:0;a:7:{s:9:"link_text";s:34:"Başka tetkik için tıklayınız.";s:9:"node_link";s:2:"19";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:71:"Başka tetkik istemiyorsanız. Yorumlamaya geçmek için tıklayınız.";s:9:"node_link";s:2:"25";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(30, 24, 'XYZ Tetkiki', NULL, 'Bu tetkik değeri normaldir.', '', 'a:2:{i:0;a:7:{s:9:"link_text";s:34:"Başka tetkik için tıklayınız.";s:9:"node_link";s:2:"19";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:71:"Başka tetkik istemiyorsanız. Yorumlamaya geçmek için tıklayınız.";s:9:"node_link";s:2:"25";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', 0, 0, 0, 1),
(31, 25, 'Yorum', NULL, '::', 'Ne düşünüyorsunuz?', 'a:2:{i:0;a:7:{s:9:"link_text";s:124:"Kişinin servika grafisi normal olarak değerlendirdim.Ancak ayrıntılı inceleme için radyoloji konsültasyonu istiyorum.";s:9:"node_link";s:2:"22";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}i:1;a:7:{s:9:"link_text";s:66:"Yorumunuzu aşağıdaki alana girip gönder tuşuna tıklayınız.";s:9:"node_link";s:2:"22";s:8:"response";s:3:"ddd";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:3:"yes";s:2:"IA";s:13:"doğru yanıt";}}', 'dal', 0, 0, 0, 1),
(33, 26, 'Doz', NULL, '::', 'Doz miktarını ve hangi uygulanacağını seçiniz.', 'a:1:{i:0;a:5:{s:9:"link_text";s:41:"Dozaj ve alım yolu tercihlerini gönder.";s:9:"node_link";s:2:"18";s:8:"response";a:3:{i:0;a:4:{s:3:"did";s:3:"117";s:3:"dmn";s:2:"50";s:3:"dmx";s:3:"250";s:4:"dval";s:3:"150";}i:1;a:4:{s:3:"did";s:4:"2248";s:3:"dmn";s:2:"50";s:3:"dmx";s:3:"250";s:4:"dval";s:2:"50";}i:2;a:4:{s:3:"did";s:2:"54";s:3:"dmn";s:2:"50";s:3:"dmx";s:3:"250";s:4:"dval";s:3:"200";}}s:4:"odul";s:0:"";s:4:"ceza";s:0:"";}}', 'dose', 0, 0, 0, 1),
(35, 27, 'yeni', NULL, NULL, NULL, 'a:1:{i:0;a:7:{s:9:"link_text";s:0:"";s:9:"node_link";s:0:"";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', NULL, NULL, NULL, 1),
(36, 28, 'yeni', NULL, NULL, NULL, 'a:1:{i:0;a:7:{s:9:"link_text";s:0:"";s:9:"node_link";s:0:"";s:8:"response";s:0:"";s:4:"odul";s:0:"";s:4:"ceza";s:0:"";s:5:"chkIA";s:2:"no";s:2:"IA";s:0:"";}}', 'dal', NULL, NULL, NULL, 1);
